#define _XOPEN_SOURCE 700
#define _POSIX_C_SOURCE 200809L
#include "br_host.h"
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <openssl/evp.h>
#include <openssl/rand.h>
#include <openssl/hmac.h>
#ifdef _WIN32
#include <io.h>
#define BR_FILENO _fileno
#define BR_COMMIT _commit
#else
#include <unistd.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <sys/file.h>
#include <limits.h>
#define BR_FILENO fileno
#define BR_COMMIT fsync
#endif
typedef struct{uint32_t h[8];uint64_t bits;uint8_t b[64];size_t n;}sha256_ctx;
static uint32_t rr(uint32_t x,unsigned n){return(x>>n)|(x<<(32-n));}
static const uint32_t K[64]={0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2};
static void shablock(sha256_ctx*c,const uint8_t*p){uint32_t w[64],a,b,d,e,f,g,h,t1,t2,cc;unsigned i;for(i=0;i<16;i++)w[i]=((uint32_t)p[4*i]<<24)|((uint32_t)p[4*i+1]<<16)|((uint32_t)p[4*i+2]<<8)|p[4*i+3];for(i=16;i<64;i++){uint32_t s0=rr(w[i-15],7)^rr(w[i-15],18)^(w[i-15]>>3),s1=rr(w[i-2],17)^rr(w[i-2],19)^(w[i-2]>>10);w[i]=w[i-16]+s0+w[i-7]+s1;}a=c->h[0];b=c->h[1];cc=c->h[2];d=c->h[3];e=c->h[4];f=c->h[5];g=c->h[6];h=c->h[7];for(i=0;i<64;i++){uint32_t S1=rr(e,6)^rr(e,11)^rr(e,25),ch=(e&f)^((~e)&g),S0=rr(a,2)^rr(a,13)^rr(a,22),maj=(a&b)^(a&cc)^(b&cc);t1=h+S1+ch+K[i]+w[i];t2=S0+maj;h=g;g=f;f=e;e=d+t1;d=cc;cc=b;b=a;a=t1+t2;}c->h[0]+=a;c->h[1]+=b;c->h[2]+=cc;c->h[3]+=d;c->h[4]+=e;c->h[5]+=f;c->h[6]+=g;c->h[7]+=h;}
static void shainit(sha256_ctx*c){static const uint32_t I[8]={0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19};memcpy(c->h,I,sizeof(I));c->bits=0;c->n=0;}
static void shaupdate(sha256_ctx*c,const uint8_t*p,size_t n){size_t z;c->bits+=(uint64_t)n*8u;while(n){z=64-c->n;if(z>n)z=n;memcpy(c->b+c->n,p,z);c->n+=z;p+=z;n-=z;if(c->n==64){shablock(c,c->b);c->n=0;}}}
static void shafinal(sha256_ctx*c,uint8_t out[32]){unsigned i;c->b[c->n++]=0x80;if(c->n>56){while(c->n<64)c->b[c->n++]=0;shablock(c,c->b);c->n=0;}while(c->n<56)c->b[c->n++]=0;for(i=0;i<8;i++)c->b[63-i]=(uint8_t)(c->bits>>(8*i));shablock(c,c->b);for(i=0;i<8;i++){out[4*i]=(uint8_t)(c->h[i]>>24);out[4*i+1]=(uint8_t)(c->h[i]>>16);out[4*i+2]=(uint8_t)(c->h[i]>>8);out[4*i+3]=(uint8_t)c->h[i];}}
static int portable_hash(void*ctx,const uint8_t*d,size_t n,uint8_t out[32]){sha256_ctx c;(void)ctx;if((n&&!d)||!out)return K20;shainit(&c);shaupdate(&c,d,n);shafinal(&c,out);return K0;}
static int openssl_verify(void*ctx,const uint8_t*k,size_t kn,const uint8_t*m,size_t mn,const uint8_t*s,size_t sn){EVP_PKEY*pk=NULL;EVP_MD_CTX*md=NULL;int ok=0;(void)ctx;if(!k||kn!=32||(!m&&mn)||!s||sn!=64)return K20;pk=EVP_PKEY_new_raw_public_key(EVP_PKEY_ED25519,NULL,k,kn);md=EVP_MD_CTX_new();if(pk&&md&&EVP_DigestVerifyInit(md,NULL,NULL,NULL,pk)==1&&EVP_DigestVerify(md,s,sn,m,mn)==1)ok=1;EVP_MD_CTX_free(md);EVP_PKEY_free(pk);return ok?K0:K23;}
static int unsupported_verify(void*ctx,const uint8_t*k,size_t kn,const uint8_t*m,size_t mn,const uint8_t*s,size_t sn){(void)ctx;(void)k;(void)kn;(void)m;(void)mn;(void)s;(void)sn;return K23;}
static const char*suffix(uint32_t o){static const char*const n[]={"state0","state1","issuer","image0","image1","stage","guest0","guest1","block"};return o>=1&&o<=9?n[o-1]:NULL;}
static int pathof(char*out,size_t cap,const char*prefix,uint32_t obj){const char*s=suffix(obj);int n;if(!out||!prefix||!s)return K20;n=snprintf(out,cap,"%s.%s",prefix,s);return n>0&&(size_t)n<cap?K0:K9;}
#ifndef _WIN32
static int canon_prefix(char*out,size_t cap,const char*in){char d[PATH_MAX],r[PATH_MAX];const char*b,*slash;size_t dl;if(!out||!in||!*in||strstr(in,"/../")||!strcmp(in,".."))return K20;slash=strrchr(in,'/');if(slash){dl=(size_t)(slash-in);if(!dl){strcpy(d,"/");}else{if(dl>=sizeof d)return K9;memcpy(d,in,dl);d[dl]=0;}b=slash+1;}else{strcpy(d,".");b=in;}if(!*b||!strcmp(b,".")||!strcmp(b,"..")||strchr(b,'/'))return K20;if(!realpath(d,r))return K4;return snprintf(out,cap,"%s/%s",r,b)>0&&strlen(r)+1+strlen(b)<cap?K0:K9;}
static int secopen(const char*p,int flags,mode_t mode){struct stat st;int fd;if(lstat(p,&st)==0&&S_ISLNK(st.st_mode)){errno=ELOOP;return-1;}fd=open(p,flags|O_CLOEXEC|O_NOFOLLOW,mode);if(fd<0)return-1;if(fstat(fd,&st)||!S_ISREG(st.st_mode)){close(fd);errno=EINVAL;return-1;}if(fchmod(fd,0600)){close(fd);return-1;}return fd;}
static int parent_sync(const char*p){char d[512],*q;int fd,rc;if(strlen(p)>=sizeof d)return K9;strcpy(d,p);q=strrchr(d,'/');if(!q)return K20;*q=0;fd=open(*d?d:"/",O_RDONLY|O_CLOEXEC|O_DIRECTORY);if(fd<0)return K4;rc=fsync(fd);close(fd);return rc?K4:K0;}
static int freadc(const char*prefix,uint32_t obj,size_t off,uint8_t*out,size_t cap,size_t*n){char p[512];struct stat st;ssize_t z;int fd;if(!out||!n||pathof(p,sizeof p,prefix,obj)!=K0)return K20;fd=secopen(p,O_RDONLY,0);if(fd<0)return K4;if(fstat(fd,&st)||off>(size_t)st.st_size){close(fd);return K4;}*n=(size_t)st.st_size-off;if(*n>cap){close(fd);return K9;}z=*n?pread(fd,out,*n,(off_t)off):0;close(fd);return z==(ssize_t)*n?K0:K4;}
static int fwritec(const char*prefix,uint32_t obj,size_t off,const uint8_t*d,size_t n){char p[512];ssize_t z;int fd;if((n&&!d)||pathof(p,sizeof p,prefix,obj)!=K0)return K20;fd=secopen(p,O_RDWR|O_CREAT,0600);if(fd<0)return K4;z=n?pwrite(fd,d,n,(off_t)off):0;if(z==(ssize_t)n&&off+n==0&&ftruncate(fd,0)!=0){close(fd);return K4;}close(fd);return z==(ssize_t)n?K0:K4;}
static int ferasec(const char*prefix,uint32_t obj){char p[512];struct stat st;if(pathof(p,sizeof p,prefix,obj)!=K0)return K20;if(lstat(p,&st)==0&&S_ISLNK(st.st_mode))return K4;if(unlink(p)==0||errno==ENOENT)return K0;return K4;}
static int fflushc(const char*prefix,uint32_t obj){char p[512];int fd,rc;if(pathof(p,sizeof p,prefix,obj)!=K0)return K20;fd=secopen(p,O_RDWR,0);if(fd<0)return K4;rc=fsync(fd);close(fd);return rc?K4:K0;}
static int fsyncc(const char*prefix,uint32_t obj){char p[512];int r;if(pathof(p,sizeof p,prefix,obj)!=K0)return K20;r=fflushc(prefix,obj);return r==K0?parent_sync(p):r;}
static int freplacec(const char*prefix,uint32_t from,uint32_t to){char a[512],b[512];struct stat st;if(pathof(a,sizeof a,prefix,from)!=K0||pathof(b,sizeof b,prefix,to)!=K0)return K20;if(lstat(a,&st)||S_ISLNK(st.st_mode)||!S_ISREG(st.st_mode))return K4;if(lstat(b,&st)==0&&S_ISLNK(st.st_mode))return K4;if(rename(a,b))return K4;return parent_sync(b);}
static int fstatusc(const char*prefix,uint32_t obj,br_storage_status*s){char p[512];struct stat st;if(!s||pathof(p,sizeof p,prefix,obj)!=K0)return K20;memset(s,0,sizeof(*s));s->capacity=N11;s->flags=BR_STORAGE_DURABLE|BR_STORAGE_ATOMIC_REPLACE|BR_STORAGE_LOCKED;if(lstat(p,&st)){return errno==ENOENT?K0:K4;}if(S_ISLNK(st.st_mode)||!S_ISREG(st.st_mode))return K4;s->size=(uint64_t)st.st_size;return K0;}
static int keypath(char*out,size_t cap,const char*prefix){int n=snprintf(out,cap,"%s.statekey",prefix);return n>0&&(size_t)n<cap?K0:K9;}
static int loadkey(br_posix_adapter*a){char p[512];int fd;ssize_t n;if(keypath(p,sizeof p,a->prefix)!=K0)return K9;fd=secopen(p,O_RDONLY,0);if(fd>=0){n=read(fd,a->state_key,32);close(fd);return n==32?K0:K4;}if(errno!=ENOENT)return K4;fd=secopen(p,O_WRONLY|O_CREAT|O_EXCL,0600);if(fd<0)return K4;if(RAND_bytes(a->state_key,32)!=1||write(fd,a->state_key,32)!=32||fsync(fd)){close(fd);unlink(p);return K4;}close(fd);return parent_sync(p);}
static int pos_read(void*c,uint32_t o,size_t x,uint8_t*b,size_t z,size_t*n){return freadc(((br_posix_adapter*)c)->prefix,o,x,b,z,n);}static int pos_write(void*c,uint32_t o,size_t x,const uint8_t*b,size_t n){return fwritec(((br_posix_adapter*)c)->prefix,o,x,b,n);}static int pos_erase(void*c,uint32_t o){return ferasec(((br_posix_adapter*)c)->prefix,o);}static int pos_flush(void*c,uint32_t o){return fflushc(((br_posix_adapter*)c)->prefix,o);}static int pos_sync(void*c,uint32_t o){return fsyncc(((br_posix_adapter*)c)->prefix,o);}static int pos_replace(void*c,uint32_t a,uint32_t b){return freplacec(((br_posix_adapter*)c)->prefix,a,b);}static int pos_status(void*c,uint32_t o,br_storage_status*s){return fstatusc(((br_posix_adapter*)c)->prefix,o,s);}
static int mono_path(char*out,size_t cap,const char*prefix){int n=snprintf(out,cap,"%s.mono",prefix);return n>0&&(size_t)n<cap?K0:K9;}
static int pos_mread(void*c,uint64_t*v){char p[512];int fd;ssize_t n;if(!v||mono_path(p,sizeof p,((br_posix_adapter*)c)->prefix)!=K0)return K20;fd=secopen(p,O_RDONLY,0);if(fd<0){*v=0;return errno==ENOENT?K0:K4;}n=read(fd,v,sizeof(*v));close(fd);return n==(ssize_t)sizeof(*v)?K0:K4;}
static int pos_mcommit(void*c,uint64_t v){char p[512],t[512];uint64_t old=0;int fd;if(pos_mread(c,&old)!=K0||v<old||mono_path(p,sizeof p,((br_posix_adapter*)c)->prefix)!=K0||snprintf(t,sizeof t,"%s.tmp",p)<=0)return N21;fd=secopen(t,O_WRONLY|O_CREAT|O_TRUNC,0600);if(fd<0)return K4;if(write(fd,&v,sizeof v)!=(ssize_t)sizeof v||fsync(fd)){close(fd);unlink(t);return K4;}close(fd);if(rename(t,p))return K4;return parent_sync(p);}
static int pos_auth(void*c,const uint8_t*d,size_t n,uint8_t out[32]){br_posix_adapter*a=c;unsigned z=0;if(!a||(!d&&n)||!out)return K20;return HMAC(EVP_sha256(),a->state_key,32,d,n,out,&z)&&z==32?K0:K5;}
static int pos_lock(void*c,uint32_t id){br_posix_adapter*a=c;char p[512];int fd;(void)id;if(!a||a->lock_fd>=0)return K7;if(snprintf(p,sizeof p,"%s.lock",a->prefix)<=0)return K9;fd=secopen(p,O_RDWR|O_CREAT,0600);if(fd<0)return K4;if(flock(fd,LOCK_EX|LOCK_NB)){close(fd);return K7;}a->lock_fd=fd;return K0;}static int pos_unlock(void*c,uint32_t id){br_posix_adapter*a=c;(void)id;if(!a||a->lock_fd<0)return K15;(void)flock(a->lock_fd,LOCK_UN);close(a->lock_fd);a->lock_fd=-1;return K0;}
#else
static int canon_prefix(char*out,size_t cap,const char*in){if(!out||!in||strlen(in)>=cap)return K20;strcpy(out,in);return K0;}
#endif
static int pos_random(void*c,uint8_t*out,size_t n){(void)c;return out&&n<=INT_MAX&&RAND_bytes(out,(int)n)==1?K0:K5;}
static int pos_clock(void*c,uint64_t*v){struct timespec t;(void)c;if(!v||clock_gettime(CLOCK_REALTIME,&t))return K5;*v=(uint64_t)t.tv_sec*1000000000ull+(uint64_t)t.tv_nsec;return K0;}static int pos_mtime(void*c,uint64_t*v){struct timespec t;(void)c;if(!v||clock_gettime(CLOCK_MONOTONIC,&t))return K5;*v=(uint64_t)t.tv_sec*1000000000ull+(uint64_t)t.tv_nsec;return K0;}
static int pos_cread(void*c,uint8_t*out,size_t cap,size_t*n){(void)c;if(!out||!n)return K20;*n=fread(out,1,cap,stdin);return ferror(stdin)?K5:K0;}
static int pos_cwrite(void*c,const uint8_t*d,size_t n){(void)c;return(!d&&n)||fwrite(d,1,n,stdout)!=n||fflush(stdout)?K5:K0;}static int pos_cflush(void*c){(void)c;return fflush(stdout)?K5:K0;}
static int echo_device(void*c,uint32_t id,uint32_t op,const uint8_t*in,size_t n,uint8_t*out,size_t cap,size_t*on){(void)c;if(!id||!op||(!in&&n)||!out||!on||n>cap)return K20;memcpy(out,in,n);*on=n;return K0;}
static void pos_panic(void*c,int code){(void)c;fprintf(stderr,"BRVM panic %d\n",code);}static int pos_yield(void*c){(void)c;return K0;}
static void fill_file_hal(br_hal*h,br_posix_adapter*a){memset(h,0,sizeof(*h));h->ctx=a;h->storage_read=pos_read;h->storage_write=pos_write;h->storage_erase=pos_erase;h->storage_flush=pos_flush;h->storage_sync=pos_sync;h->storage_replace=pos_replace;h->storage_status=pos_status;h->state_auth=pos_auth;h->monotonic_read=pos_mread;h->monotonic_commit=pos_mcommit;h->verify_signature=openssl_verify;h->random_bytes=pos_random;h->clock_read=pos_clock;h->monotonic_time=pos_mtime;h->console_read=pos_cread;h->console_write=pos_cwrite;h->console_flush=pos_cflush;h->device_call=echo_device;h->panic=pos_panic;h->yield=pos_yield;h->lock=pos_lock;h->unlock=pos_unlock;h->hash256=portable_hash;}
int br_posix_adapter_init(br_posix_adapter*a,br_hal*h,const char*prefix,uint32_t allow){if(!a||!h||!prefix)return K20;memset(a,0,sizeof(*a));a->lock_fd=-1;if(canon_prefix(a->prefix,sizeof(a->prefix),prefix)!=K0)return K20;a->allow=allow&N46;if(loadkey(a)!=K0)return K4;fill_file_hal(h,a);return K0;}
int br_windows_adapter_init(br_windows_adapter*a,br_hal*h,const char*prefix,uint32_t allow){return br_posix_adapter_init((br_posix_adapter*)a,h,prefix,allow);}
static int mem_idx(uint32_t o){return o>=1&&o<=9?(int)o-1:-1;}
static int mem_read(void*c,uint32_t o,size_t off,uint8_t*out,size_t cap,size_t*n){br_memory_adapter*a=c;int i=mem_idx(o);if(!a||i<0||!out||!n||off>a->lengths[i])return K20;*n=a->lengths[i]-off;if(*n>cap)return K9;memcpy(out,a->objects[i]+off,*n);return K0;}
static int mem_write(void*c,uint32_t o,size_t off,const uint8_t*d,size_t n){br_memory_adapter*a=c;int i=mem_idx(o);if(!a||i<0||(n&&!d)||off>BR_MEM_OBJECT_CAP||n>BR_MEM_OBJECT_CAP-off)return K9;memcpy(a->objects[i]+off,d,n);if(off+n>a->lengths[i])a->lengths[i]=off+n;return K0;}
static int mem_flush(void*c,uint32_t o){(void)c;return mem_idx(o)>=0?K0:K20;}static int mem_sync(void*c,uint32_t o){return mem_flush(c,o);}static int mem_erase(void*c,uint32_t o){br_memory_adapter*a=c;int i=mem_idx(o);if(!a||i<0)return K20;memset(a->objects[i],0,a->lengths[i]);a->lengths[i]=0;return K0;}static int mem_replace(void*c,uint32_t from,uint32_t to){br_memory_adapter*a=c;int f=mem_idx(from),t=mem_idx(to);if(!a||f<0||t<0||!a->lengths[f])return K20;memcpy(a->objects[t],a->objects[f],a->lengths[f]);a->lengths[t]=a->lengths[f];return mem_erase(c,from);}static int mem_status(void*c,uint32_t o,br_storage_status*s){br_memory_adapter*a=c;int i=mem_idx(o);if(!a||i<0||!s)return K20;s->size=a->lengths[i];s->capacity=BR_MEM_OBJECT_CAP;s->flags=BR_STORAGE_DURABLE|BR_STORAGE_ATOMIC_REPLACE|BR_STORAGE_LOCKED;s->reserved=0;return K0;}static int mem_auth(void*c,const uint8_t*d,size_t n,uint8_t out[32]){br_memory_adapter*a=c;unsigned z=0;if(!a||(!d&&n)||!out)return K20;return HMAC(EVP_sha256(),a->state_key,32,d,n,out,&z)&&z==32?K0:K5;}
static int mem_mread(void*c,uint64_t*v){br_memory_adapter*a=c;if(!a||!v)return K20;*v=a->monotonic;return K0;}static int mem_mcommit(void*c,uint64_t v){br_memory_adapter*a=c;if(!a||v<a->monotonic)return N21;a->monotonic=v;return K0;}
static int mem_random(void*c,uint8_t*out,size_t n){br_memory_adapter*a=c;size_t i;uint64_t x;if(!a||(!out&&n))return K20;x=a->rng?a->rng:0x9e3779b97f4a7c15ull;for(i=0;i<n;i++){x^=x<<13;x^=x>>7;x^=x<<17;out[i]=(uint8_t)x;}a->rng=x;return K0;}
static int mem_clock(void*c,uint64_t*v){br_memory_adapter*a=c;if(!a||!v)return K20;*v=++a->clock;return K0;}static int mem_mtime(void*c,uint64_t*v){return mem_clock(c,v);}static int mem_cread(void*c,uint8_t*out,size_t cap,size_t*n){(void)c;(void)out;(void)cap;if(!n)return K20;*n=0;return K0;}static int mem_cwrite(void*c,const uint8_t*d,size_t n){(void)c;return(!d&&n)?K20:K0;}static int mem_cflush(void*c){return c?K0:K20;}
static int mem_device(void*c,uint32_t id,uint32_t op,const uint8_t*in,size_t n,uint8_t*out,size_t cap,size_t*on){br_memory_adapter*a=c;if(!a||!id||!op||(!in&&n)||!out||!on||n>cap||(a->smartcard&&n>255))return K9;memcpy(out,in,n);*on=n;return K0;}static void mem_panic(void*c,int code){(void)c;(void)code;}static int mem_yield(void*c){br_memory_adapter*a=c;if(!a)return K20;++a->yields;return K0;}static int mem_lock(void*c,uint32_t id){br_memory_adapter*a=c;if(!a||!id)return K20;if(a->locks)return K7;a->locks=id;return K0;}static int mem_unlock(void*c,uint32_t id){br_memory_adapter*a=c;if(!a||a->locks!=id)return K15;a->locks=0;return K0;}
static void fill_mem_hal(br_hal*h,br_memory_adapter*a,int verify){memset(h,0,sizeof(*h));h->ctx=a;h->storage_read=mem_read;h->storage_write=mem_write;h->storage_erase=mem_erase;h->storage_flush=mem_flush;h->storage_sync=mem_sync;h->storage_replace=mem_replace;h->storage_status=mem_status;h->state_auth=mem_auth;h->monotonic_read=mem_mread;h->monotonic_commit=mem_mcommit;h->verify_signature=verify?openssl_verify:unsupported_verify;h->random_bytes=mem_random;h->clock_read=mem_clock;h->monotonic_time=mem_mtime;h->console_read=mem_cread;h->console_write=mem_cwrite;h->console_flush=mem_cflush;h->device_call=mem_device;h->panic=mem_panic;h->yield=mem_yield;h->lock=mem_lock;h->unlock=mem_unlock;h->hash256=portable_hash;}
int br_memory_adapter_init(br_memory_adapter*a,br_hal*h,uint32_t allow){unsigned i;if(!a||!h)return K20;memset(a,0,sizeof(*a));a->allow=allow&N46;a->rng=1;for(i=0;i<32;i++)a->state_key[i]=(uint8_t)(0x6du+i*17u);fill_mem_hal(h,a,1);return K0;}
int br_deterministic_adapter_init(br_memory_adapter*a,br_hal*h,uint32_t allow,uint64_t seed){int r=br_memory_adapter_init(a,h,allow);unsigned i;if(r==K0){a->rng=seed?seed:1;for(i=0;i<32;i++)a->state_key[i]^=(uint8_t)(a->rng>>(8u*(i&7u)));}return r;}
int br_baremetal_adapter_init(br_memory_adapter*a,br_hal*h,uint32_t allow){if(!a||!h)return K20;memset(a,0,sizeof(*a));a->allow=allow&N46;a->rng=1;fill_mem_hal(h,a,0);return K0;}
int br_smartcard_adapter_init(br_memory_adapter*a,br_hal*h,uint32_t allow){int r=br_memory_adapter_init(a,h,allow);if(r==K0)a->smartcard=1;return r;}
static void p16(uint8_t*p,uint16_t v){p[0]=(uint8_t)v;p[1]=(uint8_t)(v>>8);}static void p32(uint8_t*p,uint32_t v){p[0]=(uint8_t)v;p[1]=(uint8_t)(v>>8);p[2]=(uint8_t)(v>>16);p[3]=(uint8_t)(v>>24);}static void p64(uint8_t*p,uint64_t v){unsigned i;for(i=0;i<8;i++)p[i]=(uint8_t)(v>>(8*i));}
static void enc(uint8_t*out,const br_insn*in){out[0]=in->op;out[1]=in->mode;out[2]=in->rd;out[3]=in->ra;out[4]=in->rb;out[5]=in->cap;p16(out+6,in->flags);p64(out+8,in->imm);}
int br_host_image_write(const char*path,const br_insn*code,size_t count,const uint8_t*data,size_t dl,uint32_t v,uint32_t requested){uint8_t*image,digest[32];size_t i,payload,total;FILE*f;sha256_ctx c;if(!path||!code||!count||count>N05||dl>K3||(dl&&!data)||!v||!requested||(requested&~N46))return K20;for(i=0;i<count;i++)if(code[i].op>=N28||code[i].mode>BR_TRAPPING||code[i].cap>=N71||code[i].rd>=N43||code[i].ra>=N43||code[i].rb>=N43)return K20;payload=count*K22+dl;total=K11+payload;if(total>N20)return K7;image=calloc(total,1);if(!image)return N14;memcpy(image,"BRIM",4);image[4]=BR_ISA_MAJOR;image[5]=BR_ISA_MINOR;image[6]=BR_ABI_MAJOR;image[7]=1;image[8]=BR_IMAGE_ABI;image[9]=20;image[10]=N43;image[11]=N71;image[12]=N28;image[13]=4;p16(image+14,K11);p32(image+16,v);p32(image+20,requested);p16(image+28,(uint16_t)count);p16(image+30,(uint16_t)dl);for(i=0;i<count;i++)enc(image+K11+i*K22,code+i);if(dl)memcpy(image+K11+count*K22,data,dl);shainit(&c);shaupdate(&c,image+K11,payload);shafinal(&c,digest);memcpy(image+32,digest,32);memcpy(image+64,"Q17-BRVM-ISA41",14);f=fopen(path,"wb");if(!f){free(image);return K4;}{int ok=fwrite(image,1,total,f)==total;if(fclose(f))ok=0;free(image);return ok?K0:K4;}}
int br_host_ed25519_public(const uint8_t*priv,size_t n,uint8_t pub[32]){EVP_PKEY*k;size_t pn=32;int ok;if(!priv||n!=32||!pub)return K20;k=EVP_PKEY_new_raw_private_key(EVP_PKEY_ED25519,NULL,priv,n);if(!k)return K23;ok=EVP_PKEY_get_raw_public_key(k,pub,&pn)==1&&pn==32;EVP_PKEY_free(k);return ok?K0:K23;}
int br_host_image_sign(uint8_t*image,size_t*n,size_t cap,const uint8_t*priv,size_t kn){EVP_PKEY*k=NULL;EVP_MD_CTX*c=NULL;size_t sn=64;int ok=0;if(!image||!n||!priv||kn!=32||*n<K11||cap<*n+64||memcmp(image,"BRIM",4)||(image[7]&2))return K20;image[7]|=2;k=EVP_PKEY_new_raw_private_key(EVP_PKEY_ED25519,NULL,priv,kn);c=EVP_MD_CTX_new();if(k&&c&&EVP_DigestSignInit(c,NULL,NULL,NULL,k)==1&&EVP_DigestSign(c,image+*n,&sn,image,*n)==1&&sn==64)ok=1;EVP_MD_CTX_free(c);EVP_PKEY_free(k);if(!ok){image[7]&=(uint8_t)~2u;return K23;}*n+=64;return K0;}
