#define _POSIX_C_SOURCE 200809L
#include "brvm.h"
#include <openssl/evp.h>
#include <stdio.h>
#include <openssl/crypto.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
static const char*const opn[N28]={"NOP","MOVI","MOV","JMP","JZ","JNZ","HALT","ADD","SUB","MUL","DIVU","MODU","AND","OR","XOR","NOT","SHL","SHR","CMP","LOAD","STORE","PUSH","POP","SVC","CALL","RET","YIELD","TRAP","CAPQ","CHECKPOINT","LDX","STX"};
static const char*const mode[4]={"WRAP","CHECKED","SATURATE","TRAPPING"};
static uint16_t g16(const uint8_t*p){return(uint16_t)(p[0]|((uint16_t)p[1]<<8));}static uint32_t g32(const uint8_t*p){return(uint32_t)p[0]|((uint32_t)p[1]<<8)|((uint32_t)p[2]<<16)|((uint32_t)p[3]<<24);}static uint64_t g64(const uint8_t*p){uint64_t v=0;unsigned i;for(i=0;i<8;i++)v|=(uint64_t)p[i]<<(8*i);return v;}
static int hb(const void*d,size_t n,uint8_t o[32]){EVP_MD_CTX*c=EVP_MD_CTX_new();unsigned z=0;int ok=c&&EVP_DigestInit_ex(c,EVP_sha256(),0)==1&&EVP_DigestUpdate(c,d,n)==1&&EVP_DigestFinal_ex(c,o,&z)==1&&z==32;EVP_MD_CTX_free(c);return ok?0:-1;}static int hf(const char*p,uint8_t o[32]){FILE*f=fopen(p,"rb");EVP_MD_CTX*c=0;uint8_t b[4096];size_t n;unsigned z=0;int ok=0;if(!f)return-1;c=EVP_MD_CTX_new();if(!c||EVP_DigestInit_ex(c,EVP_sha256(),0)!=1)goto d;while((n=fread(b,1,sizeof b,f)))if(EVP_DigestUpdate(c,b,n)!=1)goto d;if(ferror(f)||EVP_DigestFinal_ex(c,o,&z)!=1||z!=32)goto d;ok=1;d:EVP_MD_CTX_free(c);fclose(f);return ok?0:-1;}static int load(const char*p,uint8_t**out,size_t*n){FILE*f;struct stat st;uint8_t*b;size_t z;int ok,fd;
if(!out||!n){return-1;}
*out=NULL;*n=0;if(!p){return-1;}
fd=open(p,O_RDONLY|O_NONBLOCK|O_NOFOLLOW);if(fd<0){return-1;}
f=fdopen(fd,"rb");if(!f){close(fd);return-1;}
if(fstat(fileno(f),&st)||!S_ISREG(st.st_mode)||st.st_size<=0||(uintmax_t)st.st_size>N20){fclose(f);return-1;}
z=(size_t)st.st_size;b=malloc(z);if(!b){fclose(f);return-1;}ok=fread(b,1,z,f)==z&&!ferror(f);if(fclose(f))ok=0;
if(!ok){OPENSSL_cleanse(b,z);free(b);return-1;}*out=b;*n=z;return 0;}
static uint32_t opcap(unsigned o){if(o<=BR_HALT||o==N72||o==BR_RET||o==BR_YIELD||o==BR_TRAP||o==BR_CAPQ)return BR_CAP_CONTROL;if(o<=BR_CMP)return BR_CAP_ARITH;if(o==BR_LOAD||o==BR_STORE||o==BR_LDX||o==BR_STX)return BR_CAP_MEMORY;if(o==BR_PUSH||o==BR_POP)return BR_CAP_STACK;if(o==N35)return N58;if(o==N16)return N00;return 0;}static uint32_t svccap(unsigned s){if(s>=N55)return 0;if(s<=3u||s==7u||s==9u||s==10u||s==11u||s==14u||s==16u||s==18u||s==19u)return N00;if(s==4u||s==5u||s==12u||s==13u||s==15u)return N00|N58;if(s==6u||s==17u)return N00|BR_CAP_DIAG;if(s==8u)return N00|N60;return 0;}static uint32_t feat(unsigned o){if(o==N72||o==BR_RET)return BR_FEAT_CALL;if(o==BR_LDX||o==BR_STX)return N67;if(o>=BR_YIELD&&o<=N35)return BR_FEAT_SYSTEM;return 0;}
static int verify(const uint8_t*im,size_t n,const char*src,const char*ir,int dis){uint16_t cc,dl;uint32_t ext,requested,need=0,features=N50|N57|BR_FEAT_TRAP_TABLE;size_t payload,expected,poff,i,k;uint8_t h[32],sh[32],bh[32],reach[N05]={0},terminal[N05]={0},sn[N05];uint16_t succ[N05][2];int ds[N05],cs[N05],q[N05],qh=0,qt=0,changed,dd[N05],cd[N05];if(n<K11||memcmp(im,"BRIM",4)||im[4]!=BR_ISA_MAJOR||!im[5]||im[5]>BR_ISA_MINOR||im[6]!=BR_ABI_MAJOR||im[8]!=BR_IMAGE_ABI||im[9]!=20||im[10]!=N43||im[11]!=N71||im[12]!=N28||im[13]!=4||g16(im+14)!=K11)return-1;if(im[7]&~(BR_IMAGE_FLAG_FACTORY|N49|N02))return-1;cc=g16(im+28);dl=g16(im+30);ext=g32(im+24);requested=g32(im+20);if(!cc||cc>N05||dl>K3||!requested||(requested&~N46)||!(im[7]&N02)||ext!=N36)return-1;payload=(size_t)cc*K22+dl+ext;expected=K11+payload+((im[7]&N49)?64u:0u);if(n!=expected||n>N20||hb(im+K11,payload,h)||memcmp(h,im+32,32))return-1;poff=K11+(size_t)cc*K22+dl;if(memcmp(im+poff,"BRPV",4)||im[poff+4]!=1||im[poff+5]!=1||im[poff+6]!=1||im[poff+7]!=BR_ISA_MAJOR||g32(im+poff+8)!=BR_CORE_ABI||g32(im+poff+12)!=BR_CORE_ABI||!g32(im+poff+16)||g32(im+poff+88)!=g32(im+16))return-1;if(src&&(hf(src,sh)||memcmp(sh,im+poff+24,32)))return-1;if(ir&&(hf(ir,bh)||memcmp(bh,im+poff+56,32)))return-1;for(i=0;i<cc;i++){const uint8_t*p=im+K11+i*K22;unsigned o=p[0],m=p[1],rd=p[2],ra=p[3],rb=p[4],cap=p[5];uint64_t imm=g64(p+8);uint32_t req;if(o>=N28||m>BR_TRAPPING||rd>=N43||ra>=N43||rb>=N43||cap!=0||g16(p+6))return-1;if((o==BR_JMP||o==BR_JZ||o==BR_JNZ||o==N72||o==BR_RET)&&imm>=cc)return-1;if((o==BR_LOAD||o==BR_STORE)&&(imm>K3-8u||(imm&7u)))return-1;if((o==BR_LDX||o==BR_STX)&&imm>UINT32_MAX)return-1;if((o==BR_SHL||o==BR_SHR)&&imm>=N32)return-1;if(o==N16&&imm>=N55)return-1;if(o==BR_CAPQ&&imm>=N71)return-1;if(o==BR_RET){int found=0;for(k=0;k<cc;k++){const uint8_t*x=im+K11+k*K22;if(x[0]==N72&&k+1u==imm){found=1;break;}}if(!found)return-1;}req=o==N16?svccap((unsigned)imm):opcap(o);if(!req)return-1;need|=req;features|=feat(o);dd[i]=o==BR_PUSH?1:o==BR_POP?-1:0;cd[i]=o==N72?1:o==BR_RET?-1:0;sn[i]=0;if(o!=BR_HALT&&o!=BR_TRAP){if(o==BR_JMP||o==N72||o==BR_RET)succ[i][sn[i]++]=(uint16_t)imm;else if(o==BR_JZ||o==BR_JNZ){succ[i][sn[i]++]=(uint16_t)imm;if(i+1<cc)succ[i][sn[i]++]=(uint16_t)(i+1);}else if(i+1<cc)succ[i][sn[i]++]=(uint16_t)(i+1);else return-1;}if(dis){printf("%zu|%s|%s|R%u|R%u|R%u|C%u|%llu|need=0x%02x|succ=",i,opn[o],mode[m],rd,ra,rb,cap,(unsigned long long)imm,req);if(!sn[i])printf(o==BR_TRAP?"TRAP":"HALT");else if(sn[i]==1)printf("%u",succ[i][0]);else printf("%u,%u",succ[i][0],succ[i][1]);putchar('\n');}}
 if(need!=requested||g32(im+poff+20)!=need||g32(im+poff+92)!=(features|(BR_ISA_MINOR<<16)|(BR_ABI_MAJOR<<24)))return-1;
 for(i=0;i<cc;i++){ds[i]=-32768;cs[i]=-32768;}
 ds[0]=0;cs[0]=0;reach[0]=1;q[qt++]=0;
 while(qh<qt){int u=q[qh++],nd=ds[u]+dd[u],nc=cs[u]+cd[u];unsigned j;if(nd<0||nd>(int)N69||nc<0||nc>(int)N75)return-1;for(j=0;j<sn[u];j++){int v=succ[u][j];if(ds[v]==-32768){ds[v]=nd;cs[v]=nc;reach[v]=1;q[qt++]=v;}else if(ds[v]!=nd||cs[v]!=nc)return-1;}}
 for(i=0;i<cc;i++){if(!reach[i])return-1;}
 for(i=0;i<cc;i++){unsigned o=im[K11+i*K22];if(o==BR_HALT||o==BR_TRAP)terminal[i]=1;}
 do{changed=0;for(i=0;i<cc;i++){if(!terminal[i]){unsigned j;for(j=0;j<sn[i];j++){if(terminal[succ[i][j]]){terminal[i]=1;changed=1;break;}}}}}while(changed);
 for(i=0;i<cc;i++){if(!terminal[i])return-1;}return 0;}
int main(int argc,char**argv){uint8_t*im=0;size_t n=0;int dis=0,rc;if(argc<2||argc>5){fprintf(stderr,"usage: %s [--disasm] IMAGE [SOURCE BRIR]\n",argv[0]);return 2;}if(!strcmp(argv[1],"--disasm")){dis=1;argv++;argc--;}if(argc!=2&&argc!=4)return 2;if(load(argv[1],&im,&n))return 1;rc=verify(im,n,argc==4?argv[2]:0,argc==4?argv[3]:0,dis);free(im);if(!dis)printf("independent BRIM verifier: %s\n",rc?"FAIL":"PASS");return rc?1:0;}
